services:
  # Backend
  - type: web
    name: gold-backend
    plan: free
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend
  - type: static_site
    name: gold-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://gold-backend-ob9o.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
